[package]
name = "common-db"
version = "0.1.0"
edition = "2021"
description = "Biblioteca compartilhada para acesso ao banco de dados criptografado"
authors = ["Clinica Medical Team <dev@clinica.med.br>"]

[dependencies]
# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "chrono", "uuid", "json"] }
uuid = { version = "1.3", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Crypto
chacha20poly1305 = "0.10"
aes-gcm = "0.10"
cipher = "0.4"
rand = "0.8"
zeroize = "1.6"

# Error Handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
sqlx-cli = "0.7"
tempfile = "3.5"

[features]
default = []
test-utils = []